## TEST Code for running and evaluating Steadiness / Cohesiveness and other metrics

#### Import packages & set dataset path

In [1]:
from helper import *
import sys
import importlib
import numpy as np

## Import Metrics
sys.path.append("/home/hj/vis2021_snc/metrics4mdp/metrics4mdp")
from provider import MDPMetricProvider

## Import SNC
sys.path.append("/home/hj/vis2021_snc/steadiness_cohesiveness")
import snc as sc





PATH_TO_DATASET = "../../dataset-generator/dataset/"

#### Pilot Dataset Load

In [2]:
mnist_umap_path = make_path(PATH_TO_DATASET, "mnist", "umap", 2, [0.5, 10])
emb_data, raw_data, label_data = get_data(mnist_umap_path)

raw_data = np.array(raw_data)
emb_data = np.array(emb_data)
label_data = np.array(label_data)


print(emb_data[:4])
print(len(emb_data))

[[11.29208279  5.92692423]
 [11.54898739  9.0832119 ]
 [11.57514477  0.06624129]
 [10.87285995  1.90799904]]
5000


#### Pilot Local Metrics Usage

In [3]:
# mlist = ["Sammon", "DTM", "DTM_KL1", "Trustworthiness", "Continuity", "MRRE_XZ", "MRRE_ZX"]
# metric_provider = MDPMetricProvider(raw_data, emb_data, mlist, 7) 
# result = metric_provider.run()
# print(result)

In [4]:
import time

## reload SNC for the testing
importlib.reload(sc)
SNC = sc.SNC

parameter = {
    "k": 50
}



snc = SNC(raw_data, emb_data, iteration=300, cluster_parameter = parameter)
snc.fit()



In [17]:
result = snc.steadiness()
result2 = snc.cohesiveness()
# print(len(result))
# print(label_data[result])

[[0.         0.71264349 0.98276655 ... 0.62025151 0.67577445 0.68245802]
 [0.71264349 0.         0.94919887 ... 0.7379196  0.70805981 0.70445137]
 [0.98276655 0.94919887 0.         ... 1.         0.97236324 0.81417026]
 ...
 [0.62025151 0.7379196  1.         ... 0.         0.73069883 0.73809812]
 [0.67577445 0.70805981 0.97236324 ... 0.73069883 0.         0.64891678]
 [0.68245802 0.70445137 0.81417026 ... 0.73809812 0.64891678 0.        ]]
[-1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1 -1 -1  0  0 -1 -1 -1 -1 -1 -1  0  1 -1
 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1  0 -1  0  2 -1 -1  0 -1 -1 -1 -1
 -1  2 -1  2 -1 -1 -1 -1 -1  1 -1  2 -1 -1 -1  2  0 -1 -1 -1  2 -1  1 -1
 -1 -1  1  2  2 -1 -1  1 -1 -1 -1 -1 -1 -1 -1  2 -1  2 -1  1  2 -1  2 -1
 -1  2 -1 -1 -1  2 -1 -1 -1 -1  2 -1 -1 -1 -1 -1 -1 -1  2 -1  0 -1 -1 -1
  2 -1 -1 -1  2 -1 -1  0 -1 -1 -1 -1 -1 -1  0 -1 -1  2 -1  2 -1 -1 -1  0
 -1 -1 -1  2]
[[0.         1.         1.         ... 1.         1.         1.        ]
 [1.         0.         1.     